title: 'Heterogeneous studies: the road to prosperity '
description: >-
  Have you ever been envious and intrigued with someone’s extensive knowledge
  when it comes to a single subject...? Well in (Heterogeneous studies) students
  will be challenged mentally, physically, emotionally in order to become
  “Adaptive under fire” 24/7.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
